- name: play level variables
  hosts: local
  connection: local
  vars:
    course : "devops with aws"
    duratio: "120hours"
    trainer: shiva
  tasks: 
  - name: print variables
    ansible.builtin.debug:
      msg: "course is {{ course }} and trainer is {{ trainer }} with {{ duration }} duration"