- name: conditions in ansible
  hosts: local
  connection: local
  vars:
    IS_LIVE: false
  tasks:
  - name: checking the when condition
    ansible.builtin.debug:
      msg: "hello vinod"
    when: IS_LIVE