- name: gathering facts
  hosts: local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  - name: check red hat or not
    ansible.builtin.debug:
      msg: "Yes os is REDHAT"
    when: ansible_facts.os_family== "RedHat"